print ('====== DESAFIO 09 ======')
n = int(input('Digite um número que mostraremos sua tabuada: '))
s = n * 1
print ('{} x 1 = {}' .format(n, s))
s = n * 2
print ('{} x 2 = {}' .format(n, s))
s = n * 3
print ('{} x 3 = {}' .format(n, s))
s = n * 4
print ('{} x 4 = {}' .format(n, s))
s = n * 5
print ('{} x 5 = {}' .format(n, s))
s = n * 6
print ('{} x 6 = {}' .format(n, s))
s = n * 7
print ('{} x 7 = {}' .format(n, s))
s = n * 8
print ('{} x 8 = {}' .format(n, s))
s = n * 9
print ('{} x 9 = {}' .format(n, s))
s = n * 10
print ('{} x 10 = {}' .format(n, s))
